const ADD_ARTICLE = 'ADD_ARTICLE';
const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
const ADD_LIKE = 'ADD_LIKE';
const FETCH_DATA = 'FETCH_DATA';
const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED';
const GET_INFO = 'GET_INFO';

export { 
  ADD_ARTICLE, REMOVE_ARTICLE, ADD_LIKE, FETCH_DATA, FETCH_DATA_PENDING, 
  FETCH_DATA_FULFILLED, FETCH_DATA_REJECTED, GET_INFO
};