const FETCH_USER = 'FETCH_USER';
const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
const GET_INFO = 'GET_INFO';

export { 
  FETCH_USER, FETCH_USER_PENDING, FETCH_USER_FULFILLED, FETCH_USER_REJECTED, GET_INFO
};