const ADD_ARTICLE = 'ADD_ARTICLE';
const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
const EDIT_ARTICLE = 'EDIT_ARTICLE';
const DATA_LOADING = 'DATA_LOADING';
const DATA_LOADED = 'DATA_LOADED';
const FETCH_DATA = 'FETCH_DATA';

export { 
  ADD_ARTICLE, REMOVE_ARTICLE, EDIT_ARTICLE, DATA_LOADED, DATA_LOADING, FETCH_DATA 
};